Adding smoke tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -242,6 +242,46 @@ jobs:
                     cat inventory.txt
                     ansible-playbook -i inventory.txt deploy-backend.yml
             - destroy-environment
+    smoke-test:
+        docker:
+            - image: python:3.7-alpine3.11
+        steps:
+            - checkout
+            - run:
+                name: Install dependencies
+                command: |
+                    apk add --update curl nodejs npm
+                    pip install awscli
+            - run:
+                name: Get backend url
+                command: |
+                    BACKEND_IP=$(aws ec2 describe-instances \
+                      --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                      --query "Reservations[*].Instances[*].PublicIpAddress" \
+                      --output text)
+            - run:
+                name: Backend smoke test.
+                command: |
+                    echo "${BACKEND_IP}"  
+                    if curl -s http://${BACKEND_IP}:3030/api/status | grep "ok"
+                    then
+                      echo "Backend Smoke Test Success"
+                      exit 0
+                    else
+                      echo "Backend Smoke Test Failed"
+                      exit 1
+                    fi
+            - run:
+                name: Frontend smoke test.
+                command: |
+                    URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com/#/employees"
+                    if curl -s ${URL} | grep "Welcome"
+                    then
+                      return 0
+                    else
+                      return 1
+                    fi
+            - destroy-environment
 
 workflows:
     default:
@@ -266,3 +306,5 @@ workflows:
                 requires: [ run-migrations ]
             - deploy-backend:
                 requires: [ run-migrations ]
+            - smoke-test:
+                requires: [ deploy-backend, deploy-frontend ]
